--// Kuo Hub | PlatoBoost Key System (FULL - Single File)
--// Delta Supported | Save Key | Auto Load

--------------------------------------------------
-- SERVICES
--------------------------------------------------
repeat task.wait() until game:IsLoaded()
local Players = game:GetService("Players")
local HttpService = game:GetService("HttpService")
local player = Players.LocalPlayer

--------------------------------------------------
-- CONFIG
--------------------------------------------------
local SERVICE_ID = 11507
local SECRET = "63eac8c9-9d9e-4015-bd8b-0fdfd0d183eb"
local REQUIRED_PREFIX = "FREE_"
local KEY_FILE = "KuoHub_Key.txt"

local SCRIPT_TO_LOAD =
"https://api.junkie-development.de/api/v1/luascripts/public/928c638552cda68b8f1112a7c2b03092f23c9394671c108463d2caa90ad1528e/download"

--------------------------------------------------
-- EXECUTOR FUNCTIONS
--------------------------------------------------
local request = request or http_request
local setclip = setclipboard or toclipboard
local gethwid = gethwid or function()
    return player.UserId
    end

    --------------------------------------------------
    -- UTILS
    --------------------------------------------------
    local function jsonEncode(t)
        return HttpService:JSONEncode(t)
        end

        local function jsonDecode(t)
            return HttpService:JSONDecode(t)
            end

            local function digest(str)
                str = tostring(str)
                    local out = {}
                        for i = 1, #str do
                                out[#out+1] = string.format("%02x", string.byte(str, i))
                                    end
                                        return table.concat(out)
                                        end

                                        local function genNonce()
                                            local s = ""
                                                for i = 1, 16 do
                                                        s ..= string.char(math.random(97, 122))
                                                            end
                                                                return s
                                                                end

                                                                --------------------------------------------------
                                                                -- FILE SYSTEM
                                                                --------------------------------------------------
                                                                local function saveKey(key)
                                                                    if writefile then
                                                                            writefile(KEY_FILE, key)
                                                                                end
                                                                                end

                                                                                local function loadKey()
                                                                                    if isfile and isfile(KEY_FILE) then
                                                                                            return readfile(KEY_FILE)
                                                                                                end
                                                                                                end

                                                                                                local function clearKey()
                                                                                                    if delfile and isfile(KEY_FILE) then
                                                                                                            delfile(KEY_FILE)
                                                                                                                end
                                                                                                                end

                                                                                                                --------------------------------------------------
                                                                                                                -- HOST DETECT
                                                                                                                --------------------------------------------------
                                                                                                                local HOST = "https://api.platoboost.app"
                                                                                                                local test = request({
                                                                                                                    Url = HOST .. "/public/connectivity",
                                                                                                                        Method = "GET"
                                                                                                                        })
                                                                                                                        if not test or test.StatusCode ~= 200 then
                                                                                                                            HOST = "https://api.platoboost.net"
                                                                                                                            end

                                                                                                                            --------------------------------------------------
                                                                                                                            -- PLATOBOOST VERIFY
                                                                                                                            --------------------------------------------------
                                                                                                                            local function redeemKey(key)
                                                                                                                                local nonce = genNonce()
                                                                                                                                    local res = request({
                                                                                                                                            Url = HOST .. "/public/redeem/" .. SERVICE_ID,
                                                                                                                                                    Method = "POST",
                                                                                                                                                            Headers = {["Content-Type"] = "application/json"},
                                                                                                                                                                    Body = jsonEncode({
                                                                                                                                                                                identifier = digest(gethwid()),
                                                                                                                                                                                            key = key,
                                                                                                                                                                                                        nonce = nonce
                                                                                                                                                                                                                })
                                                                                                                                                                                                                    })

                                                                                                                                                                                                                        if res and res.StatusCode == 200 then
                                                                                                                                                                                                                                local data = jsonDecode(res.Body)
                                                                                                                                                                                                                                        return data.success == true
                                                                                                                                                                                                                                            end
                                                                                                                                                                                                                                                return false
                                                                                                                                                                                                                                                end

                                                                                                                                                                                                                                                local function verifyKey(key)
                                                                                                                                                                                                                                                    if not key or not key:match("^" .. REQUIRED_PREFIX) then
                                                                                                                                                                                                                                                            return false
                                                                                                                                                                                                                                                                end

                                                                                                                                                                                                                                                                    local nonce = genNonce()
                                                                                                                                                                                                                                                                        local url =
                                                                                                                                                                                                                                                                                HOST .. "/public/whitelist/" .. SERVICE_ID ..
                                                                                                                                                                                                                                                                                        "?identifier=" .. digest(gethwid()) ..
                                                                                                                                                                                                                                                                                                "&key=" .. key ..
                                                                                                                                                                                                                                                                                                        "&nonce=" .. nonce

                                                                                                                                                                                                                                                                                                            local res = request({ Url = url, Method = "GET" })
                                                                                                                                                                                                                                                                                                                if not res or res.StatusCode ~= 200 then
                                                                                                                                                                                                                                                                                                                        return false
                                                                                                                                                                                                                                                                                                                            end

                                                                                                                                                                                                                                                                                                                                local data = jsonDecode(res.Body)
                                                                                                                                                                                                                                                                                                                                    if data.success and data.data.valid then
                                                                                                                                                                                                                                                                                                                                            return true
                                                                                                                                                                                                                                                                                                                                                end

                                                                                                                                                                                                                                                                                                                                                    -- FREE KEY → Redeem
                                                                                                                                                                                                                                                                                                                                                        if key:sub(1,5) == "FREE_" then
                                                                                                                                                                                                                                                                                                                                                                return redeemKey(key)
                                                                                                                                                                                                                                                                                                                                                                    end

                                                                                                                                                                                                                                                                                                                                                                        return false
                                                                                                                                                                                                                                                                                                                                                                        end

                                                                                                                                                                                                                                                                                                                                                                        --------------------------------------------------
                                                                                                                                                                                                                                                                                                                                                                        -- AUTO LOAD SAVED KEY
                                                                                                                                                                                                                                                                                                                                                                        --------------------------------------------------
                                                                                                                                                                                                                                                                                                                                                                        local saved = loadKey()
                                                                                                                                                                                                                                                                                                                                                                        if saved and verifyKey(saved) then
                                                                                                                                                                                                                                                                                                                                                                            loadstring(game:HttpGet(SCRIPT_TO_LOAD))()
                                                                                                                                                                                                                                                                                                                                                                                return
                                                                                                                                                                                                                                                                                                                                                                                else
                                                                                                                                                                                                                                                                                                                                                                                    clearKey()
                                                                                                                                                                                                                                                                                                                                                                                    end

                                                                                                                                                                                                                                                                                                                                                                                    --------------------------------------------------
                                                                                                                                                                                                                                                                                                                                                                                    -- GUI
                                                                                                                                                                                                                                                                                                                                                                                    --------------------------------------------------
                                                                                                                                                                                                                                                                                                                                                                                    local gui = Instance.new("ScreenGui", player.PlayerGui)
                                                                                                                                                                                                                                                                                                                                                                                    gui.Name = "KuoHub_KeyUI"
                                                                                                                                                                                                                                                                                                                                                                                    gui.ResetOnSpawn = false

                                                                                                                                                                                                                                                                                                                                                                                    local frame = Instance.new("Frame", gui)
                                                                                                                                                                                                                                                                                                                                                                                    frame.Size = UDim2.new(0,360,0,220)
                                                                                                                                                                                                                                                                                                                                                                                    frame.Position = UDim2.new(0.5,-180,0.5,-110)
                                                                                                                                                                                                                                                                                                                                                                                    frame.BackgroundColor3 = Color3.fromRGB(25,25,25)
                                                                                                                                                                                                                                                                                                                                                                                    frame.Active = true
                                                                                                                                                                                                                                                                                                                                                                                    frame.Draggable = true
                                                                                                                                                                                                                                                                                                                                                                                    Instance.new("UICorner", frame).CornerRadius = UDim.new(0,14)

                                                                                                                                                                                                                                                                                                                                                                                    local title = Instance.new("TextLabel", frame)
                                                                                                                                                                                                                                                                                                                                                                                    title.Size = UDim2.new(1,0,0,40)
                                                                                                                                                                                                                                                                                                                                                                                    title.BackgroundTransparency = 1
                                                                                                                                                                                                                                                                                                                                                                                    title.Text = "🔐 Kuo Hub-Key"
                                                                                                                                                                                                                                                                                                                                                                                    title.TextColor3 = Color3.new(1,1,1)
                                                                                                                                                                                                                                                                                                                                                                                    title.Font = Enum.Font.GothamBold
                                                                                                                                                                                                                                                                                                                                                                                    title.TextSize = 16

                                                                                                                                                                                                                                                                                                                                                                                    local box = Instance.new("TextBox", frame)
                                                                                                                                                                                                                                                                                                                                                                                    box.Size = UDim2.new(1,-40,0,38)
                                                                                                                                                                                                                                                                                                                                                                                    box.Position = UDim2.new(0,20,0,55)
                                                                                                                                                                                                                                                                                                                                                                                    box.PlaceholderText = "FREE_xxxxxxxx"
                                                                                                                                                                                                                                                                                                                                                                                    box.BackgroundColor3 = Color3.fromRGB(40,40,40)
                                                                                                                                                                                                                                                                                                                                                                                    box.TextColor3 = Color3.new(1,1,1)
                                                                                                                                                                                                                                                                                                                                                                                    box.Font = Enum.Font.Gotham
                                                                                                                                                                                                                                                                                                                                                                                    box.TextSize = 14
                                                                                                                                                                                                                                                                                                                                                                                    Instance.new("UICorner", box).CornerRadius = UDim.new(0,8)

                                                                                                                                                                                                                                                                                                                                                                                    local status = Instance.new("TextLabel", frame)
                                                                                                                                                                                                                                                                                                                                                                                    status.Size = UDim2.new(1,-40,0,22)
                                                                                                                                                                                                                                                                                                                                                                                    status.Position = UDim2.new(0,20,0,98)
                                                                                                                                                                                                                                                                                                                                                                                    status.BackgroundTransparency = 1
                                                                                                                                                                                                                                                                                                                                                                                    status.Text = ""
                                                                                                                                                                                                                                                                                                                                                                                    status.TextColor3 = Color3.new(1,1,1)
                                                                                                                                                                                                                                                                                                                                                                                    status.Font = Enum.Font.Gotham
                                                                                                                                                                                                                                                                                                                                                                                    status.TextSize = 13

                                                                                                                                                                                                                                                                                                                                                                                    local verifyBtn = Instance.new("TextButton", frame)
                                                                                                                                                                                                                                                                                                                                                                                    verifyBtn.Size = UDim2.new(1,-40,0,36)
                                                                                                                                                                                                                                                                                                                                                                                    verifyBtn.Position = UDim2.new(0,20,0,130)
                                                                                                                                                                                                                                                                                                                                                                                    verifyBtn.Text = "✅ Verify Key"
                                                                                                                                                                                                                                                                                                                                                                                    verifyBtn.BackgroundColor3 = Color3.fromRGB(60,60,60)
                                                                                                                                                                                                                                                                                                                                                                                    verifyBtn.TextColor3 = Color3.new(1,1,1)
                                                                                                                                                                                                                                                                                                                                                                                    verifyBtn.Font = Enum.Font.GothamBold
                                                                                                                                                                                                                                                                                                                                                                                    verifyBtn.TextSize = 14
                                                                                                                                                                                                                                                                                                                                                                                    Instance.new("UICorner", verifyBtn).CornerRadius = UDim.new(0,8)

                                                                                                                                                                                                                                                                                                                                                                                    local getBtn = Instance.new("TextButton", frame)
                                                                                                                                                                                                                                                                                                                                                                                    getBtn.Size = UDim2.new(1,-40,0,32)
                                                                                                                                                                                                                                                                                                                                                                                    getBtn.Position = UDim2.new(0,20,0,175)
                                                                                                                                                                                                                                                                                                                                                                                    getBtn.Text = "🔑 GetKey"
                                                                                                                                                                                                                                                                                                                                                                                    getBtn.BackgroundColor3 = Color3.fromRGB(45,90,160)
                                                                                                                                                                                                                                                                                                                                                                                    getBtn.TextColor3 = Color3.new(1,1,1)
                                                                                                                                                                                                                                                                                                                                                                                    getBtn.Font = Enum.Font.GothamBold
                                                                                                                                                                                                                                                                                                                                                                                    getBtn.TextSize = 13
                                                                                                                                                                                                                                                                                                                                                                                    Instance.new("UICorner", getBtn).CornerRadius = UDim.new(0,8)

                                                                                                                                                                                                                                                                                                                                                                                    --------------------------------------------------
                                                                                                                                                                                                                                                                                                                                                                                    -- BUTTON LOGIC
                                                                                                                                                                                                                                                                                                                                                                                    --------------------------------------------------
                                                                                                                                                                                                                                                                                                                                                                                    verifyBtn.MouseButton1Click:Connect(function()
                                                                                                                                                                                                                                                                                                                                                                                        local key = box.Text
                                                                                                                                                                                                                                                                                                                                                                                            status.Text = "⏳ Checking..."

                                                                                                                                                                                                                                                                                                                                                                                                task.spawn(function()
                                                                                                                                                                                                                                                                                                                                                                                                        if verifyKey(key) then
                                                                                                                                                                                                                                                                                                                                                                                                                    saveKey(key)
                                                                                                                                                                                                                                                                                                                                                                                                                                status.Text = "✅ Key ถูกต้อง (บันทึกแล้ว)"
                                                                                                                                                                                                                                                                                                                                                                                                                                            task.wait(0.5)
                                                                                                                                                                                                                                                                                                                                                                                                                                                        gui:Destroy()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    loadstring(game:HttpGet(SCRIPT_TO_LOAD))()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        status.Text = "❌ Key ไม่ถูกต้อง"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                end
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    end)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    end)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    getBtn.MouseButton1Click:Connect(function()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        local res = request({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Url = HOST .. "/public/start",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Method = "POST",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Headers = {["Content-Type"] = "application/json"},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Body = jsonEncode({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    service = SERVICE_ID,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                identifier = digest(gethwid())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            })

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if res and res.StatusCode == 200 then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        local data = jsonDecode(res.Body)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if data.success then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            setclip(data.data.url)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        status.Text = "🌐 คัดลอกลิงก์แล้ว"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                end
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    end
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    end)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("[Kuo Hub] PlatoBoost Key System Loaded ✔")
